### ISSUE TITLE
command.go:30:23: undefined: newCore

### ISSUE THREAD

**Issue by BronOS** [insidieux/inizio#15]
Run: 
` go get github.com/insidieux/inizio/cmd/inizio`

Output:
`
# github.com/insidieux/inizio/cmd/inizio/internal
../../../pkg/mod/github.com/insidieux/inizio@v1.1.1/cmd/inizio/internal/command.go:30:23: undefined: newCore
`

Go Version:
`go version`

`go version go1.16.3 darwin/amd64`

**Comment by insidieux** [comment]
Thanks for report. I'll check this bug a little bit later today

**Comment by insidieux** [comment]
If you are in a hurry, use the precompiled binaries from latest release [here](https://github.com/insidieux/inizio/releases/tag/v1.1.1)

**Comment by insidieux** [comment]
Fixed and released new version
You can get it via 

```shell
go get github.com/insidieux/inizio/cmd/inizio@v1.1.2
go: downloading github.com/insidieux/inizio v1.1.2
```
